import Vue from 'vue'
import { Tab, Tabs, Checkbox, Dialog, Search, ActionSheet, Swipe, SwipeItem, Grid, GridItem, Tabbar, TabbarItem, NavBar, Icon, Toast, Lazyload, Rate } from 'vant'

Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Lazyload)
Vue.use(Rate)
Vue.use(ActionSheet)
Vue.use(Dialog)
Vue.use(Checkbox)
Vue.use(Tab)
Vue.use(Tabs)
